### ISSUE TITLE
Roulund2005_hydro

### ISSUE THREAD

**Issue by michinegro** [psu-efd/ibScourFoam#4]
Hi, I have been trying the tutorials Roulund2005_scour and Roulund2005_hydro. I've managed to run Roulund2005_scour but I could not succeed with Roulund2005_hydro. The simulation is stuck just after this message is shown: Read constant/immersedBoundaryProperties.
Am I missing something? What is the difference between Roulund2005_scour and Roulund2005_hydro? Thanks for your help!
-------------------------------------------------------------
`Reading/calculating face flux field phi
 Selecting incompressible transport model Newtonian
Selecting turbulence model type RAS
Selecting RAS turbulence model kOmegaSSTSASIB
Selecting patchDistMethod meshWave
RAS
{
    RASModel        kOmegaSSTSASIB;
    turbulence      on;
    printCoeffs     on;
    delta           cubeRootVol;
    cubeRootVolCoeffs
    {
    }
    alphaK1         0.85;
    alphaK2         1;
    alphaOmega1     0.5;
    alphaOmega2     0.856;
    gamma1          0.555556;
    gamma2          0.44;
    beta1           0.075;
    beta2           0.0828;
    betaStar        0.09;
    a1              0.31;
    b1              1;
    c1              10;
    F3              false;
}

Selecting LES delta type cubeRootVol
No MRF models present

No finite volume options present

clearOut

Begin updating IB information
Read constant/immersedBoundaryProperties
Object 0: plane, Uses classic method
Read constant/triSurfaces
Read objects surface mesh:
Read constant/immersedBoundaryProperties`

**Comment by Yalan-Song** [comment]
Hi, thanks for testing the code. The error is because c++ cannot recognize the space between strings. In constant/immersedBoundaryProperties file, please add a dash in log law: wallFunction "log_law". I re-uploaded this file, please take a look.  
Roulund2005_hydro is the hydrodynamic case in Roulund et al., 2005. In this case, the bed is rigid. Please check figure 11-16 and Table 2 in their paper. Roulund2005_hydro is the scour case (Figure 34-35).
If you find other problems in our code or have any questions, please feel free to contact me. Thank you!

**Comment by michinegro** [comment]
Hello, thank you! It's working now.
